### PR TITLE
Switch to CLDR JSON files

### PR DESCRIPTION
**Pull request by stuwest**
This series of commits replaces the former approach of
building custom extract files from CLDR .xml files and instead uses the
.json files that CLDR now distributes. It involves data structure
changes so is fairly involved; have broken down into a few separate commits.

### CODE REVIEW

**Comment by jblz** [comment]
Howdy, @stuwest!  Looking good, but this PR is kind of tough to review due to the # of files changed...
Let's break it up.

I cherry picked the commit that added the JSON files in #8 -- if you would review that and let me know if it's good to merge, I'll do that and then rebase this pull request.

**Comment by stuwest** [comment]
https://github.com/Automattic/wp-cldr-plugin/pull/8 looks good. Yeah it's a lot of files but they're all data/assets for CLDR no code.

**Comment by stuwest** [comment]
Rather than including the files, we could also just have the plugin pull them down itself from http://www.unicode.org/Public/cldr/26.0.1/.  The disadvantage of that is you either specify the [small distribution] (http://www.unicode.org/Public/cldr/26.0.1/json.zip) which includes 20 locales and is 3.3MB compressed or you get the [huge distribution] (http://www.unicode.org/Public/cldr/26.0.1/json-full.zip) which is 713 locales and 51MB compressed.  To get something in between we'd either need some interface elements or to do it manually with the files.

**Comment by jblz** [comment]
When you get a chance, can you please do the following inside your fork:
```
git pull origin master
git commit -a  ### Write a simple commit message that says you're updating the PR
git push
```

That should update this with the changes from #8

**Comment by stuwest** [comment]
Tried but it looks like i'm already sycned. that's :
```Stu:wp-cldr-plugin stu$ git pull origin master
From https://github.com/stuwest/wp-cldr-plugin
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Stu:wp-cldr-plugin stu$ git commit -a  ### updating the PR
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
Stu:wp-cldr-plugin stu$ git push
Everything up-to-date```

Also see:
```Stu:wp-cldr-plugin stu$ git remote -v
Automattic	https://github.com/Automattic/wp-cldr-plugin.git (fetch)
Automattic	https://github.com/Automattic/wp-cldr-plugin.git (push)
origin	https://github.com/stuwest/wp-cldr-plugin.git (fetch)
origin	https://github.com/stuwest/wp-cldr-plugin.git (push)
upstream	https://github.com/Automattic/wp-cldr-plugin.git (fetch)
upstream	https://github.com/Automattic/wp-cldr-plugin.git (push)```

how about a `git pull upstream/maser`?

**Comment by jblz** [comment]
> git pull upstream/master
Yes. That's it.

**Comment by stuwest** [comment]
done

**Comment by jblz** [comment]
Closing this -- incorporated in #17

**Pull request closed without merging**
